### Célula de preparação de todos os DF's a serem estudados.

In [2]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
pd.set_option('display.max_rows', None)  # Mostra todas as linhas
pd.set_option('display.max_columns', None)  # Mostra todas as colunas

experiments = [
    pd.read_csv("Experimento-1.csv"),
    pd.read_csv("Experimento-2.csv"),
    pd.read_csv("Experimento-3.csv"),
    pd.read_csv("Experimento-4.csv"),
    pd.read_csv("Experimento-5.csv")
]
experiments[1].Heuristic.fillna("None",inplace = True)
df_infos = []
for exp in experiments:
    # Verifica se a coluna 'Heuristic' existe no DataFrame
    if 'Heuristic' in exp.columns:
        grouping_columns = ['Algorithm', 'Cost Function', 'Heuristic']
    else:
        grouping_columns = ['Algorithm', 'Cost Function']
    
    # Faz o agrupamento com base nas colunas disponíveis
    grouped = exp.groupby(grouping_columns)[['Path Cost', 'Generated Nodes', 'Visited Nodes']].agg(
        ['mean', 'median', 'std']
    )
    
    # Adiciona o resultado à lista
    df_infos.append(grouped.reset_index())

### Experimento 1: Largura vs. Profundidade vs. Custo Uniforme

In [3]:
exp1 = df_infos[0]
exp1

   Algorithm Cost Function Path Cost                      Generated Nodes  \
                                mean  median          std            mean
0        BFS            c1    196.20   190.0    98.247709          901.62
1        BFS            c2    242.40   235.0   121.366539          901.62
2        BFS            c3    215.72   206.0   108.550005          901.62
3        BFS            c4    191.36   182.0    94.834929          901.62
4        DFS            c1   3003.80  2430.0  2010.562811         1048.12
5        DFS            c2   3054.80  2472.5  2042.966521         1048.12
6        DFS            c3   3029.70  2452.0  2026.365191         1048.12
7        DFS            c4   3003.80  2429.0  2010.746445         1048.12
8   Dijkstra            c1    196.20   190.0    98.247709          908.32
9   Dijkstra            c2    242.40   235.0   121.366539          902.50
10  Dijkstra            c3    207.30   199.0   102.908568          904.90
11  Dijkstra            c4    174.02   169.0    86.332884          911.18

                      Visited Nodes
   median         std          mean median         std
0   884.0  509.261165        447.36  434.5  260.893423
1   884.0  509.261165        447.36  434.5  260.893423
2   884.0  509.261165        447.36  434.5  260.893423
3   884.0  509.261165        447.36  434.5  260.893423
4   950.0  567.292806        723.84  608.0  521.744811
5   950.0  567.292806        723.84  608.0  521.744811
6   950.0  567.292806        723.84  608.0  521.744811
7   950.0  567.292806        723.84  608.0  521.744811
8   880.0  508.216186        450.84  433.0  260.343052
9   853.0  504.282163        447.82  423.0  258.658130
10  901.5  508.407809        449.16  445.5  260.534878
11  881.0  516.051638        452.56  437.0  263.833293

### Experimento 2: Custo Uniforme vs. A*

In [4]:
exp2 = df_infos[1]
exp2

   Algorithm Cost Function Heuristic Path Cost                     \
                                          mean median         std
0          A            c1        h1    192.80  180.0  104.530827
1          A            c1        h2    192.80  180.0  104.530827
2          A            c2        h1    241.60  210.0  139.256187
3          A            c2        h2    241.60  210.0  139.256187
4          A            c3        h1    205.34  182.0  113.499008
5          A            c3        h2    205.34  182.0  113.499008
6          A            c4        h1    172.52  164.5   90.518064
7          A            c4        h2    174.90  168.0   91.185223
8   Dijkstra            c1      None    192.80  180.0  104.530827
9   Dijkstra            c2      None    241.60  210.0  139.256187
10  Dijkstra            c3      None    205.34  182.0  113.499008
11  Dijkstra            c4      None    170.62  164.5   90.219888

   Generated Nodes                    Visited Nodes
              mean median         std          mean median         std
0           559.98  365.0  667.897661        142.58   92.0  168.846880
1           448.08  291.0  511.373853        113.58   73.5  128.547949
2           778.78  483.0  863.524819        198.90  124.5  219.793526
3           624.12  357.0  716.471474        158.92   90.0  181.304664
4           596.44  361.5  697.747576        151.94   92.5  176.521885
5           379.74  218.5  434.306804         96.50   57.5  109.375080
6           365.62  207.5  444.805938         93.00   55.0  111.812343
7            92.12   73.0   63.388224         23.96   19.5   15.892445
8           836.58  668.0  552.857220        416.18  325.0  284.202694
9           839.02  646.0  574.147442        417.50  312.5  294.990436
10          839.28  710.5  567.059117        417.66  343.5  291.250829
11          847.06  673.0  558.743101        421.70  325.0  286.503214

### Experimento 3: Busca Gulosa vs. A*

In [5]:
exp3 = df_infos[2]
exp3

   Algorithm Cost Function Heuristic Path Cost                     \
                                          mean median         std
0          A            c1        h1    217.40  225.0  111.260129
1          A            c1        h2    217.40  225.0  111.260129
2          A            c2        h1    265.10  280.0  140.358470
3          A            c2        h2    265.10  280.0  140.358470
4          A            c3        h1    228.14  237.5  116.954031
5          A            c3        h2    228.14  237.5  116.954031
6          A            c4        h1    194.04  202.0   95.056580
7          A            c4        h2    197.88  209.0   97.451744
8       GBFS            c1        h1    217.40  225.0  111.260129
9       GBFS            c1        h2    217.40  225.0  111.260129
10      GBFS            c2        h1    265.10  280.0  140.358470
11      GBFS            c2        h2    265.10  280.0  140.358470
12      GBFS            c3        h1    240.00  252.5  125.022447
13      GBFS            c3        h2    237.90  251.0  123.720595
14      GBFS            c4        h1    212.38  217.0  109.229937
15      GBFS            c4        h2    213.94  222.5  106.203004

   Generated Nodes                    Visited Nodes
              mean median         std          mean median         std
0           720.56  616.0  697.418129        182.60  158.5  176.601361
1           562.86  493.0  540.287377        142.22  124.0  136.086601
2           957.46  779.0  864.258257        243.40  198.5  219.484740
3           757.30  636.5  711.567463        191.84  165.0  179.956385
4           742.10  615.5  702.838451        188.10  156.0  177.605416
5           451.88  366.0  417.523586        114.24   92.5  104.904925
6           467.46  365.0  475.604715        118.20   92.0  119.558712
7           101.12   97.0   59.508065         26.10   25.0   14.900007
8            66.60   68.0   33.207449         22.74   23.5   11.126013
9            65.94   68.0   32.047420         22.74   23.5   11.126013
10           66.60   68.0   33.207449         22.74   23.5   11.126013
11           65.94   68.0   32.047420         22.74   23.5   11.126013
12           66.60   68.0   33.207449         22.74   23.5   11.126013
13           65.94   68.0   32.047420         22.74   23.5   11.126013
14           66.60   68.0   33.207449         22.74   23.5   11.126013
15           65.94   68.0   32.047420         22.74   23.5   11.126013

### Experimento 4: Largura vs. Profundidade com Randomização da Vizinhança

In [6]:
exp4 = df_infos[3]
exp4

  Algorithm Cost Function Path Cost                      Generated Nodes  \
                               mean  median          std            mean
0       BFS            c1   230.500   225.0    93.372061        1110.940
1       BFS            c2   291.750   282.5   119.107601        1111.445
2       BFS            c3   258.755   250.0   105.335430        1108.950
3       BFS            c4   222.085   211.5    94.041784        1110.635
4       DFS            c1  2920.600  2820.0  1306.375030        1045.420
5       DFS            c2  3725.950  3792.5  1448.231237        1046.255
6       DFS            c3  3242.170  3232.5  1450.967925        1066.455
7       DFS            c4  2795.495  2655.5  1349.685212        1015.195

                      Visited Nodes
   median         std          mean median         std
0  1236.0  479.381245       555.035  618.0  247.137204
1  1236.0  477.508038       555.275  618.0  246.209412
2  1232.5  478.628849       553.990  615.5  246.764103
3  1238.5  478.671236       554.890  619.5  246.768701
4  1095.5  528.953583       621.780  566.0  408.073870
5   985.0  488.038500       614.610  498.5  397.326148
6  1146.0  520.861046       649.500  583.0  433.624493
7  1036.0  530.043202       609.230  531.5  433.660274

### Experimento 5: Caminho Mínimo Com Uma Parada A Mais

In [7]:
exp5 = df_infos[4]
exp5

  Algorithm Cost Function Heuristic Path Cost                     \
                                         mean median         std
0         A            c1        h1    278.00  270.0   94.339811
1         A            c1        h2    278.00  270.0   94.339811
2         A            c2        h1    345.00  345.0  115.578256
3         A            c2        h2    345.00  345.0  115.578256
4         A            c3        h1    294.72  312.0   97.965351
5         A            c3        h2    294.72  312.0   97.965351
6         A            c4        h1    250.24  262.0   84.448347
7         A            c4        h2    251.68  247.0   84.562955

  Generated Nodes                      Visited Nodes
             mean  median          std          mean median         std
0         1632.32  1365.0  1212.407478        413.80  349.0  307.450131
1         1268.80  1071.0   962.769659        320.76  272.0  241.132792
2         2079.84  1905.0  1361.194870        528.20  480.0  347.518824
3         1616.88  1340.0  1214.100398        409.88  339.0  308.174642
4         1703.68  1413.0  1177.688722        431.52  363.0  298.457300
5         1131.56   961.0   780.206120        286.20  241.0  196.347269
6         1309.56  1155.0   924.787862        331.08  292.0  233.654645
7          724.16   661.0   444.294542        183.64  166.0  111.888293

### Todos os DataFrames usados para as análises supraescritas.
`Remova o comentário da que desejar ver por completo!`

In [8]:
# experiments[0]
# experiments[1]
# experiments[2]
# experiments[3]
# experiments[4]