### Célula de preparação de todos os DF's a serem estudados.

In [65]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
pd.set_option('display.max_rows', None)  # Mostra todas as linhas
pd.set_option('display.max_columns', None)  # Mostra todas as colunas

experiments = [
    pd.read_csv("Experimento-1.csv"),
    pd.read_csv("Experimento-2.csv"),
    pd.read_csv("Experimento-3.csv"),
    pd.read_csv("Experimento-4.csv"),
    pd.read_csv("Experimento-5.csv")
]
experiments[1].Heuristic.fillna("None",inplace = True)
df_infos = []
for exp in experiments:
    # Verifica se a coluna 'Heuristic' existe no DataFrame
    if 'Heuristic' in exp.columns:
        grouping_columns = ['Algorithm', 'Cost Function', 'Heuristic']
    else:
        grouping_columns = ['Algorithm', 'Cost Function']
    
    # Faz o agrupamento com base nas colunas disponíveis
    grouped = exp.groupby(grouping_columns)[['Path Cost', 'Generated Nodes', 'Visited Nodes']].agg(
        ['mean', 'median', 'std']
    )
    
    # Adiciona o resultado à lista
    df_infos.append(grouped.reset_index())

### Experimento 1: Largura vs. Profundidade vs. Custo Uniforme

In [66]:
exp1 = df_infos[0]
exp1

   Algorithm Cost Function Path Cost                      Generated Nodes  \
                                mean  median          std            mean
0        BFS            c1    215.00   200.0   120.699492         1002.80
1        BFS            c2    263.00   247.5   150.864854         1002.80
2        BFS            c3    235.92   220.0   134.103499         1002.80
3        BFS            c4    207.86   193.5   115.682714         1002.80
4        DFS            c1   3164.60  2930.0  2274.223088          943.72
5        DFS            c2   3218.00  2982.5  2311.332331          943.72
6        DFS            c3   3191.94  2958.5  2293.052145          943.72
7        DFS            c4   3165.30  2934.0  2275.188777          943.72
8   Dijkstra            c1    215.00   200.0   120.699492          997.54
9   Dijkstra            c2    263.00   247.5   150.864854          977.76
10  Dijkstra            c3    225.58   212.0   125.854968          988.08
11  Dijkstra            c4    188.70   174.0   102.837151         1003.60

                       Visited Nodes
    median         std          mean median         std
0   1112.0  559.500980        500.54  546.5  288.933734
1   1112.0  559.500980        500.54  546.5  288.933734
2   1112.0  559.500980        500.54  546.5  288.933734
3   1112.0  559.500980        500.54  546.5  288.933734
4   1005.0  560.783273        604.66  566.5  437.636258
5   1005.0  560.783273        604.66  566.5  437.636258
6   1005.0  560.783273        604.66  566.5  437.636258
7   1005.0  560.783273        604.66  566.5  437.636258
8   1113.5  561.312646        497.98  547.5  289.921417
9    983.5  562.849984        488.22  484.0  290.806780
10  1033.5  557.272653        493.28  511.0  287.726914
11  1046.5  551.218465        500.90  515.5  284.344951

### Experimento 2: Custo Uniforme vs. A*

In [67]:
exp2 = df_infos[1]
exp2

   Algorithm Cost Function Heuristic Path Cost                     \
                                          mean median         std
0          A            c1        h1    186.00  180.0   86.543607
1          A            c1        h2    186.00  180.0   86.543607
2          A            c2        h1    229.30  215.0  111.107642
3          A            c2        h2    229.30  215.0  111.107642
4          A            c3        h1    197.06  180.0   92.398739
5          A            c3        h2    197.06  180.0   92.398739
6          A            c4        h1    167.22  164.0   76.314411
7          A            c4        h2    170.02  171.5   78.775447
8   Dijkstra            c1      None    186.00  180.0   86.543607
9   Dijkstra            c2      None    229.30  215.0  111.107642
10  Dijkstra            c3      None    197.06  180.0   92.398739
11  Dijkstra            c4      None    165.04  164.0   76.306568

   Generated Nodes                    Visited Nodes
              mean median         std          mean median         std
0           481.56  329.0  505.052237        121.92   83.5  127.290899
1           373.78  259.5  376.396463         94.48   66.0   94.250045
2           687.12  516.0  642.432197        174.54  130.0  163.297426
3           521.00  359.0  518.398239        131.88   90.5  130.860518
4           514.46  367.0  519.087119        130.46   92.5  131.315046
5           309.44  248.5  300.116995         78.42   64.0   75.353342
6           304.38  189.5  341.611003         77.14   49.5   85.509042
7            81.24   71.0   43.438232         21.16   19.0   10.844654
8           890.06  792.5  495.233584        440.80  389.0  254.153658
9           877.54  819.5  497.784488        434.56  400.5  255.740873
10          887.60  809.5  497.321848        439.56  396.5  255.177822
11          901.64  777.0  500.456109        446.86  381.5  256.475007

### Experimento 3: Busca Gulosa vs. A*

In [68]:
exp3 = df_infos[2]
exp3

   Algorithm Cost Function Heuristic Path Cost                     \
                                          mean median         std
0          A            c1        h1    205.20  200.0  110.291636
1          A            c1        h2    205.20  200.0  110.291636
2          A            c2        h1    252.80  242.5  134.745262
3          A            c2        h2    252.80  242.5  134.745262
4          A            c3        h1    216.12  204.5  114.208302
5          A            c3        h2    216.12  204.5  114.208302
6          A            c4        h1    182.70  188.5   94.846008
7          A            c4        h2    185.44  191.0   98.921152
8       GBFS            c1        h1    205.20  200.0  110.291636
9       GBFS            c1        h2    205.20  200.0  110.291636
10      GBFS            c2        h1    252.80  242.5  134.745262
11      GBFS            c2        h2    252.80  242.5  134.745262
12      GBFS            c3        h1    227.26  210.5  122.888004
13      GBFS            c3        h2    225.66  210.5  121.338220
14      GBFS            c4        h1    199.68  203.5  108.730417
15      GBFS            c4        h2    199.46  200.0  105.251150

   Generated Nodes                    Visited Nodes
              mean median         std          mean median         std
0           669.86  341.0  708.849773        169.58   86.0  179.081339
1           521.52  271.0  542.675580        131.60   68.5  136.171560
2           882.10  676.5  828.234051        224.12  170.0  210.576143
3           697.16  455.0  693.823960        176.62  114.5  175.363284
4           685.56  403.0  694.491714        173.64  101.5  175.562392
5           415.04  251.0  409.733610        104.94   63.5  102.852065
6           429.44  189.0  488.184231        108.50   48.0  122.542496
7            92.74   85.0   55.838254         24.12   22.0   13.992184
8            63.44   62.0   33.138029         21.52   21.0   11.029164
9            62.88   62.0   32.800348         21.52   21.0   11.029164
10           63.44   62.0   33.138029         21.52   21.0   11.029164
11           62.88   62.0   32.800348         21.52   21.0   11.029164
12           63.44   62.0   33.138029         21.52   21.0   11.029164
13           62.88   62.0   32.800348         21.52   21.0   11.029164
14           63.44   62.0   33.138029         21.52   21.0   11.029164
15           62.88   62.0   32.800348         21.52   21.0   11.029164

### Experimento 4: Largura vs. Profundidade com Randomização da Vizinhança

In [69]:
exp4 = df_infos[3]
exp4

  Algorithm Cost Function Path Cost                      Generated Nodes  \
                               mean  median          std            mean
0       BFS            c1   222.000   220.0   101.327867        1049.410
1       BFS            c2   271.500   240.0   130.066662        1051.140
2       BFS            c3   244.945   231.5   114.789569        1049.655
3       BFS            c4   215.475   211.0   100.809036        1050.425
4       DFS            c1  2906.700  2925.0  1353.908583        1117.450
5       DFS            c2  3473.950  3590.0  1596.557193         995.910
6       DFS            c3  3156.915  3257.0  1544.305024        1026.400
7       DFS            c4  2845.485  2935.5  1321.739941        1058.415

                      Visited Nodes
   median         std          mean median         std
0  1042.0  525.371323       524.450  516.0  271.961380
1  1043.0  524.588952       525.365  516.5  271.567832
2  1046.5  525.347931       524.530  518.0  271.945474
3  1045.0  524.072816       524.930  517.5  271.337956
4  1215.0  538.686013       697.475  633.5  459.418487
5  1046.0  539.166490       593.615  525.0  428.922510
6  1030.5  546.803604       620.110  526.0  436.842402
7  1104.0  542.765321       646.185  574.5  438.070519

### Experimento 5: Caminho Mínimo Com Uma Parada A Mais

In [70]:
exp5 = df_infos[4]
exp5

  Algorithm Cost Function Heuristic Path Cost                     \
                                         mean median         std
0         A            c1        h1    279.20  270.0  101.772622
1         A            c1        h2    274.40  250.0  100.460606
2         A            c2        h1    339.60  330.0  125.995370
3         A            c2        h2    336.80  305.0  127.188181
4         A            c3        h1    292.16  281.0  106.763633
5         A            c3        h2    288.08  258.0  106.029839
6         A            c4        h1    246.52  230.0   90.341076
7         A            c4        h2    247.08  234.0   86.043071

  Generated Nodes                    Visited Nodes
             mean median         std          mean median         std
0          645.76  629.0  411.110516        306.56  299.0  203.325494
1          592.88  503.0  406.975769        280.64  233.0  201.242780
2          708.32  621.0  424.335630        337.32  295.0  209.459368
3          660.64  537.0  429.548880        315.04  250.0  213.141479
4          643.60  593.0  399.414780        305.40  281.0  196.853372
5          561.00  490.0  380.358822        264.32  227.0  187.226182
6          545.64  413.0  378.407065        256.32  190.0  186.930629
7          456.88  367.0  324.439044        213.16  165.0  161.482373